version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready -U ${POSTGRES_USER}"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - ADMINER_DESIGN=nette
volumes:
  data: